services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  analytics_service:
    build: ./analytics_service
    ports:
      - "5001:5000"
    depends_on:
      - mongodb

  cart_service:
    build: ./cart_service
    ports:
      - "5002:5000"
    depends_on:
      - mongodb

  gateway_service:
    build: ./gateway_service
    ports:
      - "5003:5000"

  inventory_service:
    build: ./inventory_service
    ports:
      - "5004:5000"
    depends_on:
      - mongodb

  notification_service:
    build: ./notification_service
    ports:
      - "5005:5000"
    depends_on:
      - mongodb

  order_service:
    build: ./order_service
    ports:
      - "5006:5000"
    depends_on:
      - mongodb

  payment_service:
    build: ./payment_service
    ports:
      - "5007:5000"
    depends_on:
      - mongodb

  product_service:
    build: ./product_service
    ports:
      - "5008:5000"
    depends_on:
      - mongodb

  review_service:
    build: ./review_service
    ports:
      - "5009:5000"
    depends_on:
      - mongodb

  shipping_service:
    build: ./shipping_service
    ports:
      - "5010:5000"
    depends_on:
      - mongodb

  user_service:
    build: ./user_service
    ports:
      - "5011:5000"
    depends_on:
      - mongodb

volumes:
  mongo_data:
