name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user_service
          - product_service
          - inventory_service
          - cart_service
          - order_service
          - payment_service
          - shipping_service
          - review_service
          - notification_service
          - analytics_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.service }}
          docker build -t yourusername/${{ matrix.service }}:latest .
          docker push yourusername/${{ matrix.service }}:latest
